<section class="text-right">
	<a href="<?php echo APP_URL.'categories/add'; ?>">
		<button class="btn btn-sm btn-success">
			<span class="fa fa-plus"></span> 
			Agregar
		</button>	
	</a>
</section>
<?php if (!empty($this->categories)): ?>
	<section>
		<div class="table-responsive">
			<table class="table table-bordered table-condensed table-sm bg-white">
				<thead class="thead-dark">
					<tr>
						<th>Nombre</th>
						<th>Opciones</th>
					</tr>
				</thead>
				<tbody>
					<?php foreach ($this->categories as $category): ?>
						<tr>
							<td>
								<?php echo $category['name']; ?>
							</td>
							<td>
								<a href="<?php echo APP_URL.'categories/update/'.$category['id']; ?>">
									<button class="btn btn-sm btn-circle text-white bg-primary">
										<span class="fa fa-pen"></span>
									</button>
								</a>
								<a href="<?php echo APP_URL.'categories/delete/'.$category['id']; ?>">
									<button class="btn btn-sm btn-circle text-white bg-danger">
										<span class="fa fa-trash"></span>
									</button>
								</a>
							</td>
						</tr>
					<?php endforeach ?>
				</tbody>
			</table>
		</div>	
	</section>
<?php else: ?>
	<section>
		<div class="alert alert-primary" role="alert">
		  No hay registros de <strong>Categorias</strong>.
		</div>
	</section>
<?php endif ?>