<section class="text-right">
	<a href="<?php echo APP_URL.'transactions/add'; ?>">
		<button class="btn btn-sm btn-success">
			<span class="fa fa-plus"></span>
			Agregar
		</button>
	</a>
</section>
<?php if (!empty($this->transactions)): ?>
	<section>
		<div class="table-responsive">
			<table class="table table-sm bg-white">
				<?php $TotalAmmount=0; $InputMoney = 0; $OutputMoney=0; ?>
				<thead class="thead-dark">
					<tr>
						<th>Cuenta</th>
						<th>Categoria</th>
						<th>Descripcion</th>
						<th>Fecha</th>
						<th>Monto</th>
						<th>Opciones</th>
					</tr>
				</thead>
				<tbody>					
					<?php foreach ($this->transactions as $transaction): ?>
						<tr>
							<td>
								<?php echo $transaction['nameaccount']; ?>
							</td>
							<td>
								<?php echo $transaction['namecategory']; ?>
							</td>
							<td>
								<?php echo $transaction['description']; ?>
							</td>
							<td>
								<?php 
									$date = date_create($transaction['date']);
									echo date_format($date,'d/m/Y');
								?>
							</td>
							<td>
								<?php 
									if($transaction['amount']<0)
									{
										$OutputMoney+=-$transaction['amount'];
										echo "<span class='text-danger'><strong>$".number_format($transaction['amount'],2)."</strong></span>";	
									}
									else if($transaction['amount']>=0)
									{
										$InputMoney+=$transaction['amount'];
										echo "<span class='text-success'><strong>$".number_format($transaction['amount'],2)."</strong></span>";
									}
									$TotalAmmount += $transaction['amount'];
								?>
							</td>
							<td>	
								<a href="<?php echo APP_URL.'transactions/update/'.$transaction['id']; ?>">
									<button class="btn btn-sm btn-circle text-white bg-primary">
										<span class="fa fa-pen"></span>
									</button>
								</a>
								<a href="<?php echo APP_URL.'transactions/delete/'.$transaction['id']; ?>">
									<button class="btn btn-sm btn-circle text-white bg-danger">
										<span class="fa fa-trash"></span>
									</button>
								</a>
							</td>
						</tr>
					<?php endforeach ?>
				</tbody>
				<tfoot>
					<tr>
						<td colspan="4" class="text-right bg-low-grey none">
							<strong>Total Ingresos</strong>
						</td>
						<td >
							$<?php echo number_format($InputMoney,2); ?>
						</td>
						<td class="bg-low-grey none">
							 
						</td>
					</tr>
					<tr>
						<td colspan="4" class="text-right bg-low-grey none">
							<strong>Total Egresos</strong>
						</td>
						<td >
							$<?php echo number_format($OutputMoney,2); ?>
						</td>
						<td class="bg-low-grey none">  
							
						</td>
					</tr>	
					<tr>
						<td colspan="4" class="text-right bg-low-grey none">
							<strong>Total</strong>
						</td>
						<td >
							$<?php echo number_format($TotalAmmount,2); ?>
						</td>
						<td class="bg-low-grey none">
							
						</td>
					</tr>
				</tfoot>
			</table>	
		</div>
	</section>
<?php else: ?>
	<section>
		<div class="alert alert-primary" role="alert">
		  No hay registros de <strong>transacciones.</strong>
		</div>
	</section>
<?php endif ?>